name: tobaapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  smooth_star_rating: 1.1.1
  auto_size_text: ^2.1.0
  flutter_rating_bar: ^3.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: CairoBold
      fonts:
        - asset: fonts/Cairo_Bold.ttf
    - family: CairoLight
      fonts:
        - asset: fonts/Cairo_Light.ttf
    - family: CairoRegular
      fonts:
        - asset: fonts/Cairo_Regular.ttf
    - family: SegoeUIRegular
      fonts:
        - asset: fonts/Segoe_UI.ttf
    - family: SegoeUIBold
      fonts:
        - asset: fonts/Segoe_UI_Bold.ttf

  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/background.png
    - assets/images/tobalogo.png
    - assets/images/imagebackground.png
    - assets/images/markazmuslimah.png
    - assets/images/grouprounded.png
    - assets/images/imagebackground111.png
    - assets/navigationicons/navigation_icon1.png
    - assets/navigationicons/navigation_icon2.png
    - assets/navigationicons/navigation_icon3.png
    - assets/navigationicons/navigation_icon4.png
    - assets/navigationicons/navigation_icon5.png
    - assets/navigationicons/almukatibscreen2.png
    - assets/navigationicons/almukatibpart2.png
    - assets/images/Productimage.png
    - assets/images/houseforsell.png
    - assets/images/productchair.png
    - assets/images/cementproduct.png
    - assets/images/angleup.png
    - assets/images/angledown.png
    - assets/images/Villas.png
    - assets/images/bank.png
    - assets/images/cementlogo.png
    - assets/images/men.png
    - assets/images/cementtoba.png
    - assets/images/fb_icon.png
    - assets/images/icon_material_chat.png
    - assets/images/icon-awesome_eye.png
    - assets/images/awesome-facebook-f.png
    - assets/images/awesome-google.png

  #  fonts:
#    - family: CairoBold
#      fonts:
#        - asset: fonts/Cairo_Bold.ttf
#    - family: CairoLight
#      fonts:
#        - asset: fonts/Cairo_Light.ttf
#    - family: CairoRegular
#      fonts:
#        - asset: fonts/Cairo_Regular.ttf
#      - #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
